### ISSUE TITLE
Couldn't Update API.

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#4]
Hey there, it was warking fine literally 5 minutes ago. Maybe Twt f*ing around?

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://abs.twimg.com/responsive-web/client-web/api.80d3cb3a.js

**Comment by iSarabjitDhiman** [comment]
> Hey there, it was warking fine literally 5 minutes ago. Maybe Twt f*ing around?
> 
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://abs.twimg.com/responsive-web/client-web/api.80d3cb3a.js

Still not working? Even after the latest update? I believe its been fixed in the most recent update. Try installing it in a new python environment. Let me know if the issue still persists.

**Comment by iSarabjitDhiman** [comment]
> Hey there, it was warking fine literally 5 minutes ago. Maybe Twt f*ing around?
> 
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://abs.twimg.com/responsive-web/client-web/api.80d3cb3a.js

Hey @codilau , I guess you tried to update the api manually by initializing ApiUpdater ? Although TweeterPy is designed to update automatically everytime you import it to your project, still if you want to update it manually : make sure you have initialized TweeterPy first, before running ApiUpdater. Because it needs some request headers to update the api, and Initializing Tweeterpy will take care of those headers.

**Comment by iSarabjitDhiman** [comment]
> @iSarabjitDhiman I think there was a mashup between versions. Uninstalled and updated to 0.0.9 and API is Updated successfully now.
> Thanks!

Great. ✌️
